### ISSUE TITLE
Give others commit access

### ISSUE THREAD

**Issue by gregjones** [gregjones/httpcache#46]
@shurcooL @kr @willnorris Any objections if I add you as collaborators here?

**Comment by shurcooL** [comment]
I would like that, I want to help develop and maintain this library because I consider it the canonical Go library for http caching (and it's recommended to be used with the likes of go-github, etc.). Thank you!

I [plan to](https://github.com/shurcooL/backlog/issues/5) push one more enhancement (after getting it cleaned up and reviewed) in the short run, but no other long term plans atm (aside from helping with maintenance, as much as I can).

I will still use PRs and wait for a LGTM from another collaborator.
